<div class="row">
	<div class="span4">
		<h1 style='color:#AA1C47'>Andrés Carballo</h1>
		<h3>Ingeniero Informático</h3>
	</div>
</div>
<div class="row">
	<div class="span4">
		<p class="titlesection">Información Personal</p>
		<ul class="personal" style="margin:0">
			<li><span>Cumpleaños</span>
				<span class="pull-right">23 de Febrero de 1972</span></li>
			<li><span>Dirección</span>
				<span class="pull-right">Rúa a Seca nº12 4ºC</span></li>
			<li><span></span><span class="pull-right">CP 36002</span></li>
			<li><span class="pull-right">Pontevedra</span></li>
		</ul>
	</div>
	<div class="span4">
		<p class="titlesection">Contáctame</p>
		<ul class="contactme" style="margin:0">
			<li><span><i class="icon-phone"></i> Teléfono Fijo</span><span class="pull-right">+34 986856973</span></li>
			<li><span><i class="icon-signal"></i> Teléfono Móvil</span><span class="pull-right">+34 654069512</span></li>
			<!--<li><span><i class="icon-skype"></i> Skype</span><span class="pull-right">andres.carballo.nercellas</span></li>-->
			<li><span><i class="icon-envelope"></i> Correo electrónico</span>
				<span class="pull-right"><a href="mailto:andres.carballo@gmail.com">andres.carballo@gmail.com</a></span></li>
			<li><span><i class="icon-globe"></i> Sitio Web</span>
				<span class="pull-right"><a href="http://andrescarballo.hol.es" target="_blank">andrescarballo.hol.es</a></span></li>
		</ul>
	</div>
	<div class="span4">
		<p class="titlesection">Sígueme</p>
		<ul class="followme" style="margin:0">
			<li><span><i class="icon-twitter"></i></span>
				<span class="pull-right"><a href="https://twitter.com/AndresCarballoN" target="_blank">Twitter</a></span></li>
			<li><span><i class="icon-facebook"></i></span>
				<span class="pull-right"><a href="http://www.facebook.com/andres.nercellas" target="_blank">Facebook</a></span></li>
			<li><span><i class="icon-google-plus"></i></span>
				<span class="pull-right"><a href="http://plus.google.com/u/0/112098829231685419830" target="_blank">Google+</a></span></li>
			<li><span><i class="icon-linkedin"></i></span>
				<span class="pull-right"><a href="http://www.linkedin.com/profile/view?id=248176398" target="_blank">LinkedIn</a></span></li>
			<li><span><i class="icon-flickr"></i></span>
				<span class="pull-right"><a href="http://www.flickr.com/photos/26498141@N02" target="_blank">flickr</a></span></li>
		</ul>
	</div>
</div>
<div class="row">
	<div class="span12">
		<p class="titlesection">Localización</p>
			<iframe width="100%" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.es/maps/ms?msa=0&amp;msid=203519195061311259679.0004db719684fc0bc2434&amp;ie=UTF8&amp;ll=42.430869,-8.635061&amp;spn=0,0&amp;t=m&amp;output=embed"></iframe>
	</div>
</div>