<?php 
?>

<div class="row">
	<div class="span4">
		<h1 style='color:#AA1C47'>Andrés Carballo</h1>
	</div>
</div>
<div class="row">
	<div class="span4"></div>
	<div class="span6" style='text-align:center'>
		<h2>Welcome</h2>
		<h2>New website is coming soon</h2>
	</div>
</div>
<!--  
<div class="row">
	<div class="span4">
		<p>Lorem ipsum ad his scripta blandit partiendo, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos. Eu sit tincidunt incorrupte definitionem, vis mutat affert percipit cu, eirmod consectetuer signiferumque eu per. In usu latine equidem dolores. Quo no falli viris intellegam, ut fugit veritus placerat per. Ius id vidit volumus mandamus, vide veritus democritum te nec, ei eos debet libris consulatu.</p>
	</div>
	<div class="span4">
		<p>Lorem ipsum ad his scripta blandit partiendo, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos. Eu sit tincidunt incorrupte definitionem, vis mutat affert percipit cu, eirmod consectetuer signiferumque eu per. In usu latine equidem dolores. Quo no falli viris intellegam, ut fugit veritus placerat per. Ius id vidit volumus mandamus, vide veritus democritum te nec, ei eos debet libris consulatu.</p>
	</div>
	<div class="span4">
		<p>Lorem ipsum ad his scripta blandit partiendo,  Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos. Eu sit tincidunt incorrupte definitionem, vis mutat affert percipit cu, eirmod consectetuer signiferumque eu per. In usu latine equidem dolores. Quo no falli viris intellegam, ut fugit veritus placerat per. Ius id vidit volumus mandamus, vide veritus democritum te nec, ei eos debet libris consulatu.</p>
	</div>
</div>
-->


