<?php 
?>

<div class="row">
	<div class="span4">
		<h1 style='color:#AA1C47'>Andrés Carballo</h1>
		<h3>Software Engineer</h3>
	</div>
	<div class="span4">
		<i class="icon-comment-alt"></i>
		<span>Software engineer for </span>
	</div>
</div>
<div class="row">
	<div class="span4">
		<p class="titlesection">Education</p>
		<ul class="education" style="margin:0">
			<li class="titlepointsection">Teaching Certificate</li>
			<li><span>University of Santiago de Compostela</span>
				<a href="http://www.usc.es/" target="_blank"><i class="icon-globe"></i></a>
				<span class="pull-right">1998</span></li>
		</ul>
		<br/>
		<ul class="education" style="margin:0">
			<li class="titlepointsection">Bachelor of Computer Science</li>
			<li><span>University of Deusto</span>
				<a href="http://www.deusto.es/" target="_blank"><i class="icon-globe"></i></a>
				<span class="pull-right">1990-1996</span></li>
		</ul>
		<br/>
		<a href="http://www.zend.com/en/store/education/certification/yellow-pages.php#show-ClientCandidateID=ZEND022345" target="_blank"><img src="/assets/img/zce-php5-3-logo.gif" alt="PHP 5.3 Zend"></a>
	</div>
	<div class="span4">
		<p class="titlesection">Work experience</p>
		<ul class="workexperience" style="margin:0">
			<li class="titlepointsection">Software Engineer</li>
			<li><span>AGADIC</span>
				<a href="http://www.agadic.info/" target="_blank"><i class="icon-globe"></i></a>
				<span class="pull-right">2010-2011</span></li>
			<li>...</li>
		</ul>
		<br/>
		<ul class="skills" style="margin:0">
			<li class="titlepointsection">Software Engineer</li>
			<li><span>Coritel</span>
				<a href="http://www.coritel.es/" target="_blank"><i class="icon-globe"></i></a>
				<span class="pull-right">1998-2009</span></li>
			<li>...</li>
		</ul>
		<br/>
		<ul class="skills" style="margin:0">
			<li class="titlepointsection">Intern</li>
			<li><span>CRTVG</span>
				<a href="http://www.crtvg.es/" target="_blank"><i class="icon-globe"></i></a>
				<span class="pull-right">1997</span></li>
			<li>...</li>
		</ul>		
	</div>
	<div class="span4">
		<p class="titlesection">Skills</p>
		<ul class="skills" style="margin:0">
			<li><span>Java</span>
				<span class="pull-right"><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star-empty"></i></span>
			</li>
			<li><span>PHP</span>
				<span><a href="http://www.zend.com/en/store/education/certification/yellow-pages.php#show-ClientCandidateID=ZEND022345" target="_blank"><i class="icon-certificate"></i></a></span>
				<span class="pull-right"><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star-empty"></i></span>
			</li>
			<li><span>SQL</span>
				<span class="pull-right"><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star-empty"></i></span>
			</li>
			<li><span>VB C C#</span>
				<span class="pull-right"><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star-empty"></i><i class="icon-star-empty"></i></span>
			</li>
			<li><span>RPG Cobol AS400</span>
				<span class="pull-right"><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star-empty"></i><i class="icon-star-empty"></i></span>
			</li>
		</ul>
	</div>
	<div class="span4">
		<p class="titlesection">Languages</p>
		<ul class="languages" style="margin:0">
			<li><span>Spanish</span>
				<span class="pull-right"><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i></span>
			</li>
			<li><span>Gallego</span>
				<span class="pull-right"><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i></span>
			</li>
			<li><span>English</span>
				<span class="pull-right"><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star-empty"></i><i class="icon-star-empty"></i></span>
			</li>
			<li><span>French</span>
				<span class="pull-right"><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star-empty"></i><i class="icon-star-empty"></i><i class="icon-star-empty"></i></span>
			</li>
		</ul>
	</div>
</div>
<div class="row">
	<div class="span4">
		<p class="titlesection">Contact</p>
		<ul class="contact" style="margin:0">
			<li><i class="icon-phone"></i>+34 654069512</li>
			<li><i class="icon-envelope"></i>
				<a href="mailto:andres.carballo@gmail.com">andres.carballo@gmail.com</a>
			</li>
		</ul>
	</div>
</div>