<?php 
?>

<div class="row">
	<div class="span4">
		<h1 style='color:#AA1C47'>Andrés Carballo</h1>
		<h3>Ingeniero Informático</h3>
	</div>
	<div class="span4">
		<i class="icon-comment-alt"></i>
		<span>Apasionado de la informática y la tecnología, he convertido la vocación en afición y profesión.</span>
		<span>En los últimos años he desarrollado en infinidad de lenguajes Pascal, VB, C, C#, RPG, Cobol, Java, ASP, PHP</span>
		<p></p>
	</div>
		<div class="span4">
		<p class="titlesection">Contacto</p>
		<ul class="contact" style="margin:0">
			<li><i class="icon-phone"></i>+34 654069512</li>
			<li><i class="icon-envelope"></i>
				<a href="mailto:andres.carballo@gmail.com">andres.carballo@gmail.com</a>
			</li>
		</ul>
		<br/>
		<ul class="social-links inline">
			<li><a href="https://twitter.com/AndresCarballoN" target="_blank"><i class="icon-twitter-sign icon-2x"></i></a></li>
			<li><a href="http://www.facebook.com/andres.nercellas" target="_blank"><i class="icon-facebook-sign icon-2x"></i></a></li>
			<li><a href="http://plus.google.com/u/0/112098829231685419830" target="_blank"><i class="icon-google-plus-sign icon-2x"></i></a></li>
			<li><a href="http://www.linkedin.com/profile/view?id=248176398" target="_blank"><i class="icon-linkedin-sign icon-2x"></i></a></li>
			<!-- awessome extended more -->
			<li><a href="http://www.flickr.com/photos/26498141@N02" target="_blank"><i class="icon-flickr-sign icon-2x"></i></a></li>
		</ul> 
	</div>
</div>
<div class="row">
	<div class="span4">
		<p class="titlesection">Formación</p>
		<ul class="education" style="margin:0">
			<li class="titlepointsection">Certificado de aptitud pedagógica (CAP)</li>
			<li><span>Universidad de Santiago de Compostela</span>
				<a href="http://www.usc.es/" target="_blank"><i class="icon-globe"></i></a>
				<span class="pull-right">1998</span></li>
		</ul>
		<br/>
		<ul class="education" style="margin:0">
			<li class="titlepointsection">Ingeniería informática</li>
			<li><span>Universidad de Deusto</span>
				<a href="http://www.deusto.es/" target="_blank"><i class="icon-globe"></i></a>
				<span class="pull-right">1990-1996</span></li>
		</ul>
		<br/>
		<a href="http://www.zend.com/en/store/education/certification/yellow-pages.php#show-ClientCandidateID=ZEND022345" target="_blank"><img src="/assets/img/zce-php5-3-logo.gif" alt="PHP 5.3 Zend"></a>
	</div>
	<div class="span4">
		<p class="titlesection">Experiencia profesional</p>
		<ul class="workexperience" style="margin:0">
			<li class="titlepointsection">Ingeniero informático</li>
			<li><span>Freelance</span>
				<span class="pull-right">2012-</span></li>
			<li>Desarrollo de software</li>
		</ul>
		<br/>
		<ul class="workexperience" style="margin:0">
			<li class="titlepointsection">Ingeniero informático</li>
			<li><span>AGADIC</span>
				<a href="http://www.agadic.info/" target="_blank"><i class="icon-globe"></i></a>
				<span class="pull-right">2010-2011</span></li>
			<li>Desarrollo de software y soporte a usuarios</li>
		</ul>
		<br/>
		<ul class="skills" style="margin:0">
			<li class="titlepointsection">Ingeniero informático</li>
			<li><span>Coritel</span>
				<a href="http://www.coritel.es/" target="_blank"><i class="icon-globe"></i></a>
				<span class="pull-right">1998-2009</span></li>
			<li>Análisis y desarrollo de software en diferentes clientes:
				<dl class="dl-horizontal">
					<dt>Zurich</dt>
  					<dd>Modulo de interfaces (Java, C, Isel)</dd>
  					<dt>Royal &amp; SunAllinace</dt>
  					<dd>Departamento de arquitectura (Java, C#)</dd>
  					<dt>Telefónica</dt>
  					<dd>Mantenimiento sistema de Nómina(Meta4)</dd>
  					<dt>Accenture CIO</dt>
  					<dd>Mantenimiento sistema de Nómina y RRHH (Meta4,VB,CMS,ASP,SQL)</dd>
					<dt>PSA Citroen</dt>
  					<dd>Preparación aplicacion para el cambio al Euro (Cobol)</dd>
					<dt>Danone</dt>
  					<dd>Preparación cambio Euro y nuevo sistema de gestión de ventas (RPG)</dd>
					<dt>Pescanova</dt>
  					<dd>Preparación efecto 2000 y Euro (RPG)</dd>
				</dl>
			</li>
		</ul>
		<ul class="skills" style="margin:0">
			<li class="titlepointsection">Becario</li>
			<li><span>CRTVG</span>
				<a href="http://www.crtvg.es/" target="_blank"><i class="icon-globe"></i></a>
				<span class="pull-right">1997</span></li>
			<li>Mantenimiento de sistemas</li>
		</ul>		
	</div>
	<div class="span4">
		<p class="titlesection">Conocimientos</p>
		<ul class="skills" style="margin:0">
			<li><span>Java</span>
				<span class="pull-right"><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star-empty"></i></span>
			</li>
			<li><span>PHP</span>
				<span><a href="http://www.zend.com/en/store/education/certification/yellow-pages.php#show-ClientCandidateID=ZEND022345" target="_blank"><i class="icon-certificate"></i></a></span>
				<span class="pull-right"><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star-empty"></i></span>
			</li>
			<li><span>SQL</span>
				<span class="pull-right"><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star-empty"></i></span>
			</li>
			<li><span>VB C C#</span>
				<span class="pull-right"><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star-empty"></i><i class="icon-star-empty"></i></span>
			</li>
			<li><span>RPG Cobol AS400</span>
				<span class="pull-right"><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star-empty"></i><i class="icon-star-empty"></i></span>
			</li>
		</ul>
	</div>
	<div class="span4">
		<p class="titlesection">Idiomas</p>
		<ul class="languages" style="margin:0">
			<li><span>Español</span>
				<span class="pull-right"><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i></span>
			</li>
			<li><span>Gallego</span>
				<span class="pull-right"><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i></span>
			</li>
			<li><span>Inglés</span>
				<span class="pull-right"><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star-empty"></i><i class="icon-star-empty"></i></span>
			</li>
			<li><span>Francés</span>
				<span class="pull-right"><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star-empty"></i><i class="icon-star-empty"></i><i class="icon-star-empty"></i></span>
			</li>
		</ul>
	</div>
</div>